version: '3.8'

services:
  backend:
    build: ./CultureArc-backend
    container_name: culturearc-backend
    ports:
      - "5000:5000"
    env_file:
      - ./CultureArc-backend/.env
    restart: always

  frontend:
    build: ./CultureArc-frontend
    container_name: culturearc-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
